import type { OrbitalElements } from '../engine'
import { MOON_RADIUS_KM } from '../engine'
import type { Orbiter, SurfaceObjectCategory } from './types'

const degToRad = (deg: number) => (deg * Math.PI) / 180

/**
 * Apollo crewed landing sites. Coordinates (selenographic lat/lon, east
 * positive) from each mission's official NASA landing-site report.
 */
const APOLLO_LANDINGS: SurfaceObjectCategory['objects'] = [
  {
    id: 'apollo-11',
    name: 'Apollo 11 (Tranquility Base)',
    mission: 'Apollo 11',
    agency: 'NASA',
    date: '1969-07-20',
    status: 'inactive',
    description: 'First crewed Moon landing; Armstrong and Aldrin spent ~21.5 hours on the surface.',
    latitudeDeg: 0.6875,
    longitudeDeg: 23.4333,
  },
  {
    id: 'apollo-12',
    name: 'Apollo 12',
    mission: 'Apollo 12',
    agency: 'NASA',
    date: '1969-11-19',
    status: 'inactive',
    description: 'Landed within walking distance of the unmanned Surveyor 3 probe.',
    latitudeDeg: -3.0124,
    longitudeDeg: -23.4216,
  },
  {
    id: 'apollo-14',
    name: 'Apollo 14',
    mission: 'Apollo 14',
    agency: 'NASA',
    date: '1971-02-05',
    status: 'inactive',
    description: 'Landed in the Fra Mauro highlands, the intended target of the aborted Apollo 13.',
    latitudeDeg: -3.6453,
    longitudeDeg: -17.4712,
  },
  {
    id: 'apollo-15',
    name: 'Apollo 15',
    mission: 'Apollo 15',
    agency: 'NASA',
    date: '1971-07-30',
    status: 'inactive',
    description: 'First mission to use the Lunar Roving Vehicle, near Hadley Rille.',
    latitudeDeg: 26.1008,
    longitudeDeg: 3.6527,
  },
  {
    id: 'apollo-16',
    name: 'Apollo 16',
    mission: 'Apollo 16',
    agency: 'NASA',
    date: '1972-04-21',
    status: 'inactive',
    description: 'Landed in the Descartes highlands to sample volcanic material that turned out not to be volcanic.',
    latitudeDeg: -8.9734,
    longitudeDeg: 15.5011,
  },
  {
    id: 'apollo-17',
    name: 'Apollo 17',
    mission: 'Apollo 17',
    agency: 'NASA',
    date: '1972-12-11',
    status: 'inactive',
    description: 'Final crewed Moon landing to date, in the Taurus-Littrow valley.',
    latitudeDeg: 20.1653,
    longitudeDeg: 30.7658,
  },
]

/**
 * Robotic landers and rovers. Coordinates from each mission's landing-site
 * publication (NASA/Roscosmos/CNSA mission reports).
 */
const ROBOTIC_LANDERS: SurfaceObjectCategory['objects'] = [
  {
    id: 'surveyor-1',
    name: 'Surveyor 1',
    mission: 'Surveyor program',
    agency: 'NASA',
    date: '1966-06-02',
    status: 'inactive',
    description: 'First US soft landing on another world.',
    latitudeDeg: -2.474,
    longitudeDeg: -43.339,
  },
  {
    id: 'surveyor-3',
    name: 'Surveyor 3',
    mission: 'Surveyor program',
    agency: 'NASA',
    date: '1967-04-20',
    status: 'inactive',
    description: 'Later visited by the Apollo 12 crew, who retrieved parts of it.',
    latitudeDeg: -2.94,
    longitudeDeg: -23.34,
  },
  {
    id: 'surveyor-5',
    name: 'Surveyor 5',
    mission: 'Surveyor program',
    agency: 'NASA',
    date: '1967-09-11',
    status: 'inactive',
    description: 'First in-situ chemical analysis of lunar soil.',
    latitudeDeg: 1.41,
    longitudeDeg: 23.18,
  },
  {
    id: 'surveyor-6',
    name: 'Surveyor 6',
    mission: 'Surveyor program',
    agency: 'NASA',
    date: '1967-11-10',
    status: 'inactive',
    description: 'First liftoff/hop of a spacecraft from the lunar surface, to test the technique.',
    latitudeDeg: 0.49,
    longitudeDeg: -1.4,
  },
  {
    id: 'surveyor-7',
    name: 'Surveyor 7',
    mission: 'Surveyor program',
    agency: 'NASA',
    date: '1968-01-10',
    status: 'inactive',
    description: 'Final and most scientifically capable Surveyor mission, near Tycho crater.',
    latitudeDeg: -40.86,
    longitudeDeg: -11.44,
  },
  {
    id: 'luna-9',
    name: 'Luna 9',
    mission: 'Luna program',
    agency: 'Soviet space program',
    date: '1966-02-03',
    status: 'inactive',
    description: 'First spacecraft to achieve a soft landing on the Moon (or any other body).',
    latitudeDeg: 7.08,
    longitudeDeg: -64.37,
  },
  {
    id: 'luna-13',
    name: 'Luna 13',
    mission: 'Luna program',
    agency: 'Soviet space program',
    date: '1966-12-24',
    status: 'inactive',
    description: 'Measured soil density and radiation levels after a soft landing.',
    latitudeDeg: 18.87,
    longitudeDeg: -62.05,
  },
  {
    id: 'luna-16',
    name: 'Luna 16',
    mission: 'Luna program',
    agency: 'Soviet space program',
    date: '1970-09-20',
    status: 'inactive',
    description: 'First robotic sample-return mission from another world.',
    latitudeDeg: -0.68,
    longitudeDeg: 56.3,
  },
  {
    id: 'luna-17',
    name: 'Luna 17 (Lunokhod 1)',
    mission: 'Luna program',
    agency: 'Soviet space program',
    date: '1970-11-17',
    status: 'inactive',
    description: 'Delivered Lunokhod 1, the first roving remote-controlled robot on another world.',
    latitudeDeg: 38.28,
    longitudeDeg: -35.0,
  },
  {
    id: 'luna-20',
    name: 'Luna 20',
    mission: 'Luna program',
    agency: 'Soviet space program',
    date: '1972-02-21',
    status: 'inactive',
    description: 'Second Soviet robotic sample-return mission, from the lunar highlands.',
    latitudeDeg: 3.53,
    longitudeDeg: 56.55,
  },
  {
    id: 'luna-21',
    name: 'Luna 21 (Lunokhod 2)',
    mission: 'Luna program',
    agency: 'Soviet space program',
    date: '1973-01-15',
    status: 'inactive',
    description: 'Delivered Lunokhod 2, which set the off-Earth roving distance record for over 40 years.',
    latitudeDeg: 25.85,
    longitudeDeg: 30.45,
  },
  {
    id: 'luna-24',
    name: 'Luna 24',
    mission: 'Luna program',
    agency: 'Soviet space program',
    date: '1976-08-18',
    status: 'inactive',
    description: 'Final Luna mission; returned the last Soviet lunar samples until Luna 25/Chang’e follow-ons.',
    latitudeDeg: 12.25,
    longitudeDeg: 62.2,
  },
  {
    id: 'change-3',
    name: "Chang'e 3 (Yutu)",
    mission: "Chang'e 3",
    agency: 'CNSA',
    date: '2013-12-14',
    status: 'inactive',
    description: 'First soft landing on the Moon since 1976; delivered the Yutu rover.',
    latitudeDeg: 44.12,
    longitudeDeg: -19.51,
  },
  {
    id: 'change-4',
    name: "Chang'e 4 (Yutu-2)",
    mission: "Chang'e 4",
    agency: 'CNSA',
    date: '2019-01-03',
    status: 'active',
    description: 'First landing on the lunar far side, in Von Kármán crater; Yutu-2 is still roving.',
    latitudeDeg: -45.46,
    longitudeDeg: 177.6,
  },
  {
    id: 'change-5',
    name: "Chang'e 5",
    mission: "Chang'e 5",
    agency: 'CNSA',
    date: '2020-12-01',
    status: 'inactive',
    description: 'Returned the first new lunar samples to Earth since Luna 24.',
    latitudeDeg: 43.06,
    longitudeDeg: -51.92,
  },
]

export const MOON_SURFACE_OBJECT_CATEGORIES: SurfaceObjectCategory[] = [
  {
    id: 'moon-apollo',
    label: 'Apollo landings',
    note: 'NASA crewed missions (1969–1972) — 6 sites',
    color: 0xfbbf24,
    objects: APOLLO_LANDINGS,
  },
  {
    id: 'moon-robotic',
    label: 'Robotic landers & rovers',
    note: 'Surveyor, Luna, and Chang’e missions — 14 sites',
    color: 0x38bdf8,
    objects: ROBOTIC_LANDERS,
  },
]

const circularElements = (
  semiMajorAxisKm: number,
  inclinationDeg: number,
  raanDeg: number,
): OrbitalElements => ({
  semiMajorAxisKm,
  eccentricity: 0,
  inclinationRad: degToRad(inclinationDeg),
  raanRad: degToRad(raanDeg),
  argOfPerigeeRad: 0,
  trueAnomalyRad: 0,
})

/**
 * Active/notable lunar orbiters. Elements are approximate osculating values
 * from published mission parameters (see `Orbiter` doc comment) - real
 * mapping/relay orbits drift and get adjusted over a mission's lifetime.
 */
export const MOON_ORBITERS: Orbiter[] = [
  {
    id: 'lro',
    name: 'Lunar Reconnaissance Orbiter',
    mission: 'LRO',
    agency: 'NASA',
    date: '2009-06-18',
    status: 'active',
    description: 'Polar mapping orbiter; its imagery underlies most modern lunar cartography.',
    elements: circularElements(MOON_RADIUS_KM + 50, 90, 0),
  },
  {
    id: 'chandrayaan-2-orbiter',
    name: 'Chandrayaan-2 Orbiter',
    mission: 'Chandrayaan-2',
    agency: 'ISRO',
    date: '2019-08-20',
    status: 'active',
    description: 'Polar mapping orbiter that continued science after its lander/rover crashed.',
    elements: circularElements(MOON_RADIUS_KM + 100, 90, 120),
  },
  {
    id: 'queqiao-2',
    name: 'Queqiao-2',
    mission: "Chang'e 6 relay",
    agency: 'CNSA',
    date: '2024-03-20',
    status: 'active',
    description: 'Relay satellite in a highly elliptical frozen orbit, enabling far-side communication.',
    elements: {
      semiMajorAxisKm: 6187.4,
      eccentricity: 0.6706,
      inclinationRad: degToRad(54.7),
      raanRad: degToRad(240),
      argOfPerigeeRad: degToRad(270),
      trueAnomalyRad: 0,
    },
  },
]
